
from collections import OrderedDict

processes_per_systematic = {
'lumi': 'all',
'rate_ttbar': 'TTbar',
'rate_dy': 'DYJets',
'rate_ttv': 'TTV',
'rate_diboson': 'Diboson',
'rate_singletop': 'SingleTop',
'rate_wjets': 'WJets',
'rate_qcd': 'QCD',
'rate_HH': 'HHtoWWbbSL_cHHH1',
'rate_cHHH0': 'HHtoWWbbSL_cHHH0',
'rate_cHHH1': 'HHtoWWbbSL_cHHH1',
'rate_cHHH2p45': 'HHtoWWbbSL_cHHH2p45',
'rate_cHHH5': 'HHtoWWbbSL_cHHH5',
'pu': 'all',
'pdf': 'all',
'muid': 'all',
'muiso': 'all',
'mutrigger': 'all',
'eleid': 'all',
'elereco': 'all',
'eletrigger': 'all',
'btag_bc': 'all',
'btag_udsg': 'all',
'JEC': 'all',
'JER': 'all',
'scale_TTbar': 'TTbar',
'scale_DYJets': 'DYJets',
'scale_WJets': 'WJets',
'scale_TTV': 'TTV',
'scale_Diboson': 'Diboson',
'scale_SingleTop': 'SingleTop'
}

pdf_per_systematic = {
'lumi': 'lnN',
'pu': 'shape',
'pdf': 'shape',
'muid': 'shape',
'muiso': 'shape',
'mutrigger': 'shape',
'eleid': 'shape',
'elereco': 'shape',
'eletrigger': 'shape',
'btag_bc': 'shape',
'btag_udsg': 'shape',
'JEC': 'shape',
'JER': 'shape',
'rate_ttbar': 'lnN',
'rate_dy': 'lnN',
'rate_ttv': 'lnN',
'rate_diboson': 'lnN',
'rate_singletop': 'lnN',
'rate_wjets': 'lnN',
'rate_qcd': 'lnN',
'rate_HH': 'lnN',
'rate_cHHH0': 'lnN',
'rate_cHHH1': 'lnN',
'rate_cHHH2p45': 'lnN',
'rate_cHHH5': 'lnN',
'scale_TTbar': 'shape',
'scale_DYJets': 'shape',
'scale_WJets': 'shape',
'scale_TTV': 'shape',
'scale_Diboson': 'shape',
'scale_SingleTop': 'shape'
}

value_per_systematic = {
'lumi': 1.025,
'pu': 1,
'pdf': 1,
'muid': 1,
'muiso': 1,
'mutrigger': 1,
'eleid': 1,
'elereco': 1,
'eletrigger': 1,
'btag_bc': 1,
'btag_udsg': 1,
'JEC': 1,
'JER': 1,
'rate_ttbar': 1.056,
'rate_dy': 1.1,
'rate_ttv': 1.25,
'rate_diboson': 1.2,
'rate_singletop': 1.1,
'rate_wjets': 1.25,
'rate_qcd': 1.5,
'rate_HH': 1.03,
'rate_cHHH0': '0.82/1.08',
'rate_cHHH1': '0.77/1.06',
'rate_cHHH2p45': '0.73/1.06',
'rate_cHHH5': '0.87/1.18',
'scale_TTbar': 1,
'scale_DYJets': 1,
'scale_WJets': 1,
'scale_TTV': 1,
'scale_Diboson': 1,
'scale_SingleTop': 1
}

#signaltag = 'HHtoWWbbSemiLeptonic'
signaltag = 'HHtoWWbbSL'

yeartags = {
2016: '2016v3',
2017: '2017v2',
2018: '2018'
}
