
from collections import OrderedDict

processes_per_systematic = {
    'lumi': 'all',
    'rate_ttbar': 'TTbar', # old rate uncertainties, should not be used
    'rate_dy': 'DYJets',
    'rate_ttv': 'TTV',
    'rate_diboson': 'Diboson',
    'rate_singletop': 'SingleTop',
    'rate_wjets': 'WJets',
    'rate_qcd': 'QCD', # only QCD uncertainty
    'rate_scales_tt': 'TTbar,TTV',
    'rate_scales_t': 'SingleTop',
    'rate_scales_V': 'WJets,DYJets',
    'rate_scales_VV': 'Diboson',
    'rate_scales_HH': 'ggHH_kl_0_kt_1_hbbhww,ggHH_kl_1_kt_1_hbbhww,ggHH_kl_1_kt_2p45_hbbhww,ggHH_kl_5_kt_1_hbbhww',
    'rate_pdf_gg': 'ggHH_kl_0_kt_1_hbbhww,ggHH_kl_1_kt_1_hbbhww,ggHH_kl_2p45_kt_1_hbbhww,ggHH_kl_5_kt_1_hbbhww,TTbar', # TTZ
    'rate_pdf_qq': 'WJets,DYJets,Diboson', # TTW
    'rate_pdf_gq': 'SingleTop',
    'rate_pdf_ttv': 'TTV',
    'pu': 'all',
    'pdf': 'all', # inclusive shape pdf, should not be used
    'muid': 'all',
    'muiso': 'all',
    'mutrigger': 'all',
    'eleid': 'all',
    'elereco': 'all',
    'eletrigger': 'all',
    'btag_bc': 'all',
    'btag_udsg': 'all',
    'JEC': 'all',
    #'JER': 'all',
    'JER': 'ggHH_kl_0_kt_1_hbbhww,ggHH_kl_1_kt_1_hbbhww,ggHH_kl_2p45_kt_1_hbbhww,ggHH_kl_5_kt_1_hbbhww,TTbar,SingleTop,DYJets,WJets,TTV,Diboson',
    'scale_TTbar': 'TTbar',
    'scale_SingleTop': 'SingleTop',
    'scale_DYJets': 'DYJets',
    'scale_WJets': 'WJets',
    'scale_TTV': 'TTV',
    'scale_Diboson': 'Diboson',
    'pdf_TTbar': 'TTbar',
    'pdf_SingleTop': 'SingleTop',
    'pdf_DYJets': 'DYJets',
    'pdf_WJets': 'WJets',
    'pdf_TTV': 'TTV',
    'pdf_Diboson': 'Diboson',
    'scale_HH': 'ggHH_kl_0_kt_1_hbbhww,ggHH_kl_1_kt_1_hbbhww,ggHH_kl_2p45_kt_1_hbbhww,ggHH_kl_5_kt_1_hbbhww',
    'pdf_HH': 'ggHH_kl_0_kt_1_hbbhww,ggHH_kl_1_kt_1_hbbhww,ggHH_kl_2p45_kt_1_hbbhww,ggHH_kl_5_kt_1_hbbhww',
}

pdf_per_systematic = {
    'lumi': 'lnN',
    'pu': 'shape',
    'pdf': 'shape',
    'muid': 'shape',
    'muiso': 'shape',
    'mutrigger': 'shape',
    'eleid': 'shape',
    'elereco': 'shape',
    'eletrigger': 'shape',
    'btag_bc': 'shape',
    'btag_udsg': 'shape',
    'JEC': 'shape',
    'JER': 'shape',
    'rate_ttbar': 'lnN',
    'rate_dy': 'lnN',
    'rate_ttv': 'lnN',
    'rate_diboson': 'lnN',
    'rate_singletop': 'lnN',
    'rate_wjets': 'lnN',
    'rate_qcd': 'lnN',
    'rate_scales_tt': 'lnN',
    'rate_scales_t': 'lnN',
    'rate_scales_V': 'lnN',
    'rate_scales_VV': 'lnN',
    'rate_scales_HH': 'lnN',
    'rate_pdf_gg': 'lnN',
    'rate_pdf_qq': 'lnN',
    'rate_pdf_gq': 'lnN',
    'rate_pdf_ttv': 'lnN',
    'scale_TTbar': 'shape',
    'scale_SingleTop': 'shape',
    'scale_DYJets': 'shape',
    'scale_WJets': 'shape',
    'scale_TTV': 'shape',
    'scale_Diboson': 'shape',
    'pdf_TTbar': 'shape',
    'pdf_SingleTop': 'shape',
    'pdf_DYJets': 'shape',
    'pdf_WJets': 'shape',
    'pdf_TTV': 'shape',
    'pdf_Diboson': 'shape',
    'scale_HH': 'shape',
    'pdf_HH': 'shape'
}

correlateYears = {
    'lumi': False,
    'pu': False,
    'pdf': False,
    'muid': False,
    'muiso': False,
    'mutrigger': False,
    'eleid': False,
    'elereco': False,
    'eletrigger': False,
    'btag_bc': False,
    'btag_udsg': False,
    'JEC': False,
    'JER': False,
    'rate_ttbar': True,
    'rate_dy': True,
    'rate_ttv': True,
    'rate_diboson': True,
    'rate_singletop': True,
    'rate_wjets': True,
    'rate_qcd': True,
    'rate_scales_tt': True,
    'rate_scales_t': True,
    'rate_scales_V': True,
    'rate_scales_VV': True,
    'rate_scales_HH': True,
    'rate_pdf_gg': True,
    'rate_pdf_qq': True,
    'rate_pdf_gq': True,
    'rate_pdf_ttv': True,
    'scale_TTbar': True,
    'scale_SingleTop': True,
    'scale_DYJets': True,
    'scale_WJets': True,
    'scale_TTV': True,
    'scale_Diboson': True,
    'pdf_TTbar': True,
    'pdf_SingleTop': True,
    'pdf_DYJets': True,
    'pdf_WJets': True,
    'pdf_TTV': True,
    'pdf_Diboson': True,
    'scale_HH': True,
    'pdf_HH': True
}
'''
correlateYears = {
    'lumi': True,
    'pu': True,
    'pdf': True,
    'muid': True,
    'muiso': True,
    'mutrigger': True,
    'eleid': True,
    'elereco': True,
    'eletrigger': True,
    'btag_bc': True,
    'btag_udsg': True,
    'JEC': True,
    'JER': True,
    'rate_ttbar': True,
    'rate_dy': True,
    'rate_ttv': True,
    'rate_diboson': True,
    'rate_singletop': True,
    'rate_wjets': True,
    'rate_qcd': True,
    'rate_scales_tt': True,
    'rate_scales_t': True,
    'rate_scales_V': True,
    'rate_scales_VV': True,
    'rate_scales_HH': True,
    'rate_pdf_gg': True,
    'rate_pdf_qq': True,
    'rate_pdf_gq': True,
    'rate_pdf_ttv': True,
    'scale_TTbar': True,
    'scale_SingleTop': True,
    'scale_DYJets': True,
    'scale_WJets': True,
    'scale_TTV': True,
    'scale_Diboson': True,
    'pdf_TTbar': True,
    'pdf_SingleTop': True,
    'pdf_DYJets': True,
    'pdf_WJets': True,
    'pdf_TTV': True,
    'pdf_Diboson': True,
    'scale_HH': True,
    'pdf_HH': True
}
'''
# TODO: scale and pdf Diboson/TTV: combine to scale_other and pdf_other
value_per_systematic_and_process = {
    tuple(['lumi', 'all']): 1.025,
    tuple(['pu', 'all']): 1,
    tuple(['muid', 'all']): 1,
    tuple(['muiso', 'all']): 1,
    tuple(['mutrigger', 'all']): 1,
    tuple(['eleid', 'all']): 1,
    tuple(['elereco', 'all']): 1,
    tuple(['eletriger', 'all']): 1,
    tuple(['btag_bc', 'all']): 1,
    tuple(['btag_udsg', 'all']): 1,
    tuple(['JEC', 'all']): 1,
    #tuple(['JER', 'all']): 1,
    tuple(['JER', 'ggHH_kl_0_kt_1_hbbhww']): 1,
    tuple(['JER', 'ggHH_kl_1_kt_1_hbbhww']): 1,
    tuple(['JER', 'ggHH_kl_2p45_kt_1_hbbhww']): 1,
    tuple(['JER', 'ggHH_kl_5_kt_1_hbbhww']): 1,
    tuple(['JER', 'TTbar']): 1,
    tuple(['JER', 'SingleTop']): 1,
    tuple(['JER', 'WJets']): 1,
    tuple(['JER', 'DYJets']): 1,
    tuple(['JER', 'Diboson']): 1,
    tuple(['JER', 'TTV']): 1,
    tuple(['rate_qcd', 'QCD']): 1.50,
    tuple(['rate_scales_tt', 'TTbar']): '0.965/1.024',
    tuple(['rate_scales_tt', 'TTV']): '0.8715/1.168', # ttW: '0.836/1.255', ttZ: '0.927/1.081'
    tuple(['rate_scales_t', 'SingleTop']): '0.979/1.031',
    tuple(['rate_scales_V', 'WJets']): '0.996/1.008',
    tuple(['rate_scales_V', 'DYJets']): 1.002,
    tuple(['rate_scales_VV', 'Diboson']): 1.030,
    tuple(['rate_scales_HH', 'ggHH_kl_0_kt_1_hbbhww']): '0.82/1.08',
    tuple(['rate_scales_HH', 'ggHH_kl_1_kt_1_hbbhww']): '0.77/1.06',
    tuple(['rate_scales_HH', 'ggHH_kl_2p45_kt_1_hbbhww']): '0.73/1.06',
    tuple(['rate_scales_HH', 'ggHH_kl_5_kt_1_hbbhww']): '0.87/1.18',
    tuple(['rate_pdf_gg', 'ggHH_kl_0_kt_1_hbbhww']): 1.030,
    tuple(['rate_pdf_gg', 'ggHH_kl_1_kt_1_hbbhww']): 1.030,
    tuple(['rate_pdf_gg', 'ggHH_kl_2p45_kt_1_hbbhww']): 1.030,
    tuple(['rate_pdf_gg', 'ggHH_kl_5_kt_1_hbbhww']): 1.030,
    tuple(['rate_pdf_gg', 'TTbar']): 1.042,
    tuple(['rate_pdf_gq', 'SingleTop']): 1.028,
    tuple(['rate_pdf_qq', 'WJets']): 1.038,
    tuple(['rate_pdf_qq', 'DYJets']): 1.020,
    tuple(['rate_pdf_qq', 'Diboson']): 1.05,
    tuple(['rate_pdf_ttv', 'TTV']): 1.0355, # ttW: 1.036, ttZ: 1.035
    tuple(['scale_TTbar', 'TTbar']): 1,
    tuple(['scale_SingleTop', 'SingleTop']): 1,
    tuple(['scale_WJets', 'WJets']): 1,
    tuple(['scale_DYJets', 'DYJets']): 1,
    tuple(['scale_TTV', 'TTV']): 1,
    tuple(['scale_Diboson', 'Diboson']): 1,
    tuple(['pdf_TTbar', 'TTbar']): 1,
    tuple(['pdf_SingleTop', 'SingleTop']): 1,
    tuple(['pdf_WJets', 'WJets']): 1,
    tuple(['pdf_DYJets', 'DYJets']): 1,
    tuple(['pdf_TTV', 'TTV']): 1,
    tuple(['pdf_Diboson', 'Diboson']): 1,
    tuple(['scale_HH', 'ggHH_kl_0_kt_1_hbbhww']): 1,
    tuple(['scale_HH', 'ggHH_kl_1_kt_1_hbbhww']): 1,
    tuple(['scale_HH', 'ggHH_kl_2p45_kt_1_hbbhww']): 1,
    tuple(['scale_HH', 'ggHH_kl_5_kt_1_hbbhww']): 1,
    tuple(['pdf_HH', 'ggHH_kl_0_kt_1_hbbhww']): 1,
    tuple(['pdf_HH', 'ggHH_kl_1_kt_1_hbbhww']): 1,
    tuple(['pdf_HH', 'ggHH_kl_2p45_kt_1_hbbhww']): 1,
    tuple(['pdf_HH', 'ggHH_kl_5_kt_1_hbbhww']): 1,
}

value_per_systematic = {
    'lumi': 1.025,
    'pu': 1,
    'pdf': 1,
    'muid': 1,
    'muiso': 1,
    'mutrigger': 1,
    'eleid': 1,
    'elereco': 1,
    'eletrigger': 1,
    'btag_bc': 1,
    'btag_udsg': 1,
    'JEC': 1,
    'JER': 1,
    'rate_ttbar': 1.056,
    'rate_dy': 1.1,
    'rate_ttv': 1.25,
    'rate_diboson': 1.2,
    'rate_singletop': 1.1,
    'rate_wjets': 1.25,
    'rate_qcd': 1.5,
    'scale_TTbar': 1,
    'scale_DYJets': 1,
    'scale_WJets': 1,
    'scale_TTV': 1,
    'scale_Diboson': 1,
    'scale_SingleTop': 1
}

#signaltag = 'HHtoWWbbSemiLeptonic'
#signaltag = 'HHtoWWbbSL'
signaltag = 'ggHH_kl_X_kt_1_hbbhww'


yeartags = {
    2016: '2016v3',
    2017: '2017v2',
    2018: '2018',
    'Incl': 'Incl',
}
